# builds python
---
- hosts: localhost
  connection: local
  become: yes
  become_method: sudo
  gather_facts: yes
  vars:
    python_version: 3.9.2
  tasks:
    - name: apt dependencies are installed
      apt:
        pkg:
          - build-essential
          - libreadline-gplv2-dev
          - libncursesw5-dev
          - libssl-dev
          - libsqlite3-dev
          - tk-dev
          - libgdbm-dev
          - libc6-dev
          - libbz2-dev
          - libffi-dev
          - zlib1g-dev
        state: latest
        update_cache: yes
      when: ansible_distribution == 'Debian'

    - name: source and archive directories present
      file:
        path: "/opt/{{ item }}"
        state: directory
      with_items:
        - archives
        - sources

    - name: download latest python
      get_url:
        url: "https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tar.xz"
        dest: "/opt/archives/Python-{{ python_version }}.tar.xz"
        force: no
      register: download

    - name: extract python archive
      unarchive:
        src: "/opt/archives/Python-{{ python_version }}.tar.xz"
        dest: "/opt/sources/"
      when: download.changed

    - name: build python
      shell: "cd /opt/sources/Python-{{ python_version }} && ./configure --prefix=\"/opt/Python-{{ python_version }}\" && make && make install"
      when: download.changed
